name: build

on:
  pull_request:
  push:
    branches: master

jobs:
  test:
    name: Run Tests
    runs-on: windows-latest # TODO: Ubuntu currently broken.
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./.github/actions/checkout_submodules

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Run tests
        run: bash ./gradlew test

      - name: Run lint
        run: bash ./gradlew ktlintCheck

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
