name: Execute checks

on:
  pull_request:
  push:
    branches: master

jobs:
  test:
    name: Run Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./.github/actions/checkout_submodules

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      # TODO: Without this step, the build fails with the following error:
      # Execution failed for task ':common:verifyDebugDatabaseMigration'.
      # > A failure occurred while executing app.cash.sqldelight.gradle.VerifyMigrationTask$VerifyMigrationAction
      #   > No suitable driver found for jdbc:sqlite:
      - name: Run verifyDebugDatabase
        run: bash ./gradlew verifyDebugDatabaseMigration

      - name: Run check
        run: bash ./gradlew check

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
